### ISSUE TITLE
Can't get the lambda working

### ISSUE THREAD

**Issue by karl0ss** [josephschmitt/alexa-couchpotato#22]
I can't seem to get the lambda working on this one, I have done the alexa-sickbeard and that works fine...I seem to have a couple of issues...

The npm run bundle fails on my windows machine (worked fine for alexe-sickbeard, so I packaged the zip myself, with the index.js/.env/node_modules/lib dir and uploaded to my lambda, when I make a request its returning with - 

{
  "errorMessage": "Unexpected reserved word",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Module._compile (module.js:373:25)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

Any idea?

Thanks

**Comment by karl0ss** [comment]
Does anyone have a lambda.zip that works that doesn't include their .env so I can update it with mine...

I have just tired to do the npm run bundle on a ubuntu machine and that also fails, so something is broken somewhere

**Comment by alexc-MSFT** [comment]
There's something broken in the package.json - I had to tweak it a bit but still couldn't get it to built so built it partly using bestzip and partly manually. 
I do have a working Lambda zip - I can add it at some point.

Sent from Outlook for iOS




On Mon, Dec 5, 2016 at 2:16 PM +0000, "Karl Hudgell" <notifications@github.com> wrote:












Does anyone have a lambda.zip that works that doesn't include their .env so I can update it with mine...


I have just tired to do the npm run bundle on a ubuntu machine and that also fails, so something is broken somewhere

**Comment by karl0ss** [comment]
Brilliant, thank you so much, I will keep an eye for when you posted it, thank you :)

**Comment by karl0ss** [comment]
Any chance of that zip please @sharepointalex ?

**Comment by karl0ss** [comment]
I managed to create a working zip by manually running commands from the package.json.

**Comment by alexc-MSFT** [comment]
Sorry I was travelling - that's what I did to build a working zip

**Comment by bsollenb54** [comment]
Hey @karl0ss or @sharepointalex would either of you be willing to share a working zip minus your .env?

Im hitting issues with npm run bundle

**Comment by josephschmitt** [comment]
@karl0ss @bsollenb54 @sharepointalex I've started including pre-packaged zip files along with the releases. They include everything you need to upload to lambda. Just edit the `.env` file inside, re-zip, and upload. https://github.com/josephschmitt/alexa-couchpotato/releases/
