### ISSUE TITLE
Skill test works, live trial gives same answer all the time

### ISSUE THREAD

**Issue by dariokan82** [josephschmitt/alexa-couchpotato#23]
If I test the skill on the Dev portal, it works (albeit with error "The Response is invalid" if I try an add before asking if the movie is on the list).

When I try with my echo dot, even if the name of the correct movie is recognised, Alexa will always reply with "hm, it appears that [Name of first movie in my movie list] is already on the list".

No error in the logs.

Any clue?

**Comment by alexc-MSFT** [comment]
I think this is currently broken from memory - there was a pull request raised to fix it (I think). It's been a while since I contributed to this repo. I'll have to check and get back to you.

**Comment by alexc-MSFT** [comment]
Clone the moviename-fix branch - this has the fix in it for this issue.

**Comment by dariokan82** [comment]
Thanks, I will try the fix today! 👍

**Comment by Yardl3y** [comment]
I have the same problem with Alexa saying "It looks like [Name of first movie in my movie list] is already on the list". This seems to happen with more complicated titles, e.g. Donnie Darko, Sing Street. More straight forward titles such as "Paris is Burning" or "Silence" work fine. This is happening when asking if something is on my list, the "add" function is much more stable.

**Comment by alexc-MSFT** [comment]
See my fork - https://github.com/sharepointalex/alexa-couchpotato. Going to try and fix this.

**Comment by Yardl3y** [comment]
Thank you, I will keep an eye on that.

**Comment by josephschmitt** [comment]
I _think_ this is fixed in [v1.2.1](https://github.com/josephschmitt/alexa-couchpotato/releases/tag/v1.2.1). Let me know if it's still an issue.
