### ISSUE TITLE
A Newbie Guide?

### ISSUE THREAD

**Issue by hernandito** [josephschmitt/alexa-couchpotato#24]
Hi Joseph,

I just got my Echo, and have a been a long-time user of CP. While not a complete newbie when it comes to programming and coding, I am definitely not an expert either. Alexa skill stuff is completely new to me.

I have watched tutorials and I cannot seem to make the connection between those tutorials and your Alexa-Couchpotato repo and guide.

Could I impose on you for a more basic/detailed walk-through on how to implement your skill and what one has to do in the Amazon Developers New Skill process? If you prefer, I could do a fully illustrated guide myself if you simply tell me something like:

Name: Couchpotato
Invocation Name: couch potato
Intent Schema: paste contents of x.json. Edit to X add your url
Add Slot type: 
Enter Type:
Enter Values: paste xyz here
etc....

Also, not sure where (per your instructions) do I place a and edit the .ev file.

I know this is a lot to ask, but I think it would make this easier for masses. I promise to also link to it in all the relevant forums I am a member of.

I also think that it would make it easier to learn, and possibly for the end user to implement other skills from other repos. Like the Alexa-Sonos.

Many thanks for this, and for any help you can provide.

H.

**Comment by josephschmitt** [comment]
@hernandito I was hoping the current README had enough info for this to not be necessary, but maybe not. Would you mind walking me through what steps you've taken so far and where you got stuck? That should help me figure out what parts of the README need updating.

**Comment by josephschmitt** [comment]
@hernandito I added some more detail to the README and also updated it for Amazon's new UI. Let me know if that helps.
