### ISSUE TITLE
The remote endpoint could not be called

### ISSUE THREAD

**Issue by Yardl3y** [josephschmitt/alexa-couchpotato#25]
Total newbie here, I scrambled along and got everything set up. When testing the skill through the service simulator, I'm getting "The remote endpoint could not be called, or the response it returned was invalid." Most "if" requests do work though, a few dont, if I type in "if friday is on the list" it returns the above error. "Add" doesn't work for me with anything, for example "to add kedi to the list" returns "The response is invalid". Any help would be greatly appreciated.

**Comment by alexc-MSFT** [comment]
I've forked this repo as it's not been updated for a while - https://github.com/sharepointalex/alexa-couchpotato. Keep an eye out here, i'm going to make some fixes and do some testing to try and resolve this issue.

**Comment by josephschmitt** [comment]
@sharepointalex I _think_ this is fixed in [v1.2.0](https://github.com/josephschmitt/alexa-couchpotato/releases/tag/v1.2.0). Let me know if it's still an issue.

**Comment by josephschmitt** [comment]
@Yardl3y I think this is fixed now. Make sure to update and re-read the README, as there are new scripts to package everything up.
