### ISSUE TITLE
babel src -d dist issue

### ISSUE THREAD

**Issue by bsollenb54** [josephschmitt/alexa-couchpotato#27]
I'm trying to manually install the devdependencies and dependencies then run the scripts via CMD as administrator and it's saying no such node, operation, or program exists, even when I try executing it from the node_modules/.bin/ folder.

I've hit a few roadblocks at this point, so I'm hoping someone who has gotten there's zipped and deployed to a AWS lambda function would be generous enough to upload their working .ZIP file with the dependencies in the project (removed of the .env) so I can just add my own .env and upload it too.

Thanks!

**Comment by josephschmitt** [comment]
@bsollenb54 can you give me some more info on your setup? what OS are you on? version of node?

**Comment by josephschmitt** [comment]
@bsollenb54 if you grab the latest, there's now a `package` script that should do all this for you. Just run `npm install` and then `npm run package`. It _should_ generate a ZIP file with everything you'd need to upload to Lambda.

**Comment by bsollenb54** [comment]
I was on win7 using nodejs6.10....I actually ended up creating a lambda function and uploading the .zip with the config/default.json updated per your latest instructions. Works like a charm! Thanks for all of your work!
