### ISSUE TITLE
"The response is invalid"

### ISSUE THREAD

**Issue by cherowley** [josephschmitt/alexa-couchpotato#3]
If I type "is X men Apocolypse on the list" in the service simulator I get this response:

"The response is invalid"

How do I fix this to give a better spoken response? :)

Otherwise, great app!

**Comment by alexc-MSFT** [comment]
I'm currently working on making some modifications to the skill - this will fix this error in addition to some others (i've tested and confirmed).  

Just out of interest, send an AddMovie intent test event on the AWS Lambda console and let me know what comes back.

I'm also adding other functionality such as searching by year, different phrases etc.

**Comment by alexc-MSFT** [comment]
Also - I think I found out this was caused by the fact this skill returns so much JSON, too much for Alexa to handle - i've slimed this down and it works much better.

**Comment by cherowley** [comment]
Brilliant cheers :) I'll try doing the addmovie on the lamda in a bit :)

**Comment by cherowley** [comment]
BTW asking is "x men Apocalypse on the list" works fine - my spelling isn't great!

**Comment by alexc-MSFT** [comment]
Ok so it's just AddMovie that's not working for you? Let me know what the test event comes back as. I think the FindMovie (is) returns a small amount of JSON which is why it works.

**Comment by cherowley** [comment]
Ok, I admit that all this online stuff is new to me so pretty much fumbling my way through cuttin' and pastin' with alexa /lambda for the time being!

Another dumb error by me - removing "movie" from the request worked fine in the service simulator...

Just me figuring out how the sample utterances can be used :)

**Comment by alexc-MSFT** [comment]
Ah yes, you just need to write 'add {moviename}' etc. the service simulator will add any other required phrases. 

I think if you use it on an echo you will find you get an invalid response for movies when there are more than one returned. I've fixed this with cutting down the size of the returned response.

**Comment by cherowley** [comment]
Yep get the problem as you said - will you be releasing the updated code soon? :)

**Comment by alexc-MSFT** [comment]
Just submitted a pull request to @josephschmitt for the fixed code - it only works for AddMovie currently, I need to sort it for find movie.
