### ISSUE TITLE
Error when testing skill

### ISSUE THREAD

**Issue by markrennie71** [josephschmitt/alexa-couchpotato#31]
Hello, thanks for the updated version. I can get a kodi skill I added working but when I add this one and go to test it, I get the error in Service Response
The remote endpoint could not be called, or the response it returned was invalid.

Any idea please?

Cheers
Mark

**Comment by josephschmitt** [comment]
@markrennie71 is your server accessible from outside your network?

**Comment by markrennie71** [comment]
yeah it is, I started again and now works when you test it in Alexa skills kit development console, but when I say to Alexa/Echo it doesn't recognise the skill, even though it is listed.. frustrating. :)

**Comment by josephschmitt** [comment]
I know they had an outage a week or so ago due to a bug, could be you're running into it. Also just FYI I deprecated this project in favor of a fork of it that is more future proof https://josephschmitt.github.io/alexa-libby/

Might want to switch over before you get too far along here.

**Comment by markrennie71** [comment]
ahh perfect thank you.. brilliant work by the way

**Comment by josephschmitt** [comment]
also try using the skill builder beta for the interaction model. that seemed to help getting around some issues. instructions for that in the README
