### ISSUE TITLE
Use Amazon's native Alexa JavaScript sdk instead of the alexa-app project

### ISSUE THREAD

**Issue by josephschmitt** [josephschmitt/alexa-couchpotato#7]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs

The alexa-app project has gotten us far, but time to use the official project now.

**Comment by alexc-MSFT** [comment]
This looks painful! I've checked out the native Alexa JS sdk and whilst it looks good, it doesn't appear to be able to test locally (at least not easily from what i've seen?) Let me know when you get going with it, I'd like to use it for some of my other skills i'm developing but have no idea where to start! And I rely on being able to test locally.

**Comment by josephschmitt** [comment]
Yea, decided against this. The `alexa-app` project is now using the official SDK under the hood, so no need for us to do it.
